<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CarsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('cars')->insert([
            [
                // 1
                'name' => 'Ford Mustang',
                'brand_id' => '5',
                'category_id' => '4',
                'price' => '34105',
                'description' => 'The arrival of a new Mustang signals a new era for American pony car performance. The 2024 Mustang gets new engines, updated looks, and a big injection of technology. Still offered as a coupe and convertible, the 2024 Mustang uses the S650 chassis code (the last one was internally called the S550). Competition includes gas-powered rear-drive sports cars like the Dodge Challenger and Toyota GR Supra.  ',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['mustang1.jpg', 'mustang2.jpg', 'mustang3.jpg', 'mustang4.jpg', 'mustang5.jpg']),
                'avatar' => 'mustang-nobg.png',
                'slug' => Str::slug('Ford Mustang ' . '2024'),
            ],
            [
                // 2
                'name' => 'Lamborghini Huracan',
                'brand_id' => '7',
                'category_id' => '10',
                'price' => '234405',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2023',
                'images' => json_encode(['huracan1.jpg', 'huracan2.jpg', 'huracan3.jpg', 'huracan4.jpg', 'huracan5.jpg']),
                'avatar' => 'huracan-nobg.png',
                'slug' => Str::slug('Lamborghini Huracan ' . '2023'),
            ],
            [
                // 3
                'name' => 'McLaren 720S',
                'brand_id' => '8',
                'category_id' => '11',
                'price' => '330993',
                'description' => '',
                'quantity' => '2',
                'producing_year' => '2023',
                'images' => json_encode(['720s1.jpg', '720s2.jpg', '720s3.jpg', '720s4.jpg', '720s5.jpg']),
                'avatar' => '720s-nobg.png',
                'slug' => Str::slug('McLaren 720S ' . '2023'),
            ],
            [
                // 4
                'name' => 'Nissan GT-R',
                'brand_id' => '9',
                'category_id' => '10',
                'price' => '140277',
                'description' => '',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['gtr1.jpg', 'gtr2.jpg', 'gtr3.jpg', 'gtr4.jpg', 'gtr5.jpg']),
                'avatar' => 'gtr-nobg.png',
                'slug' => Str::slug('Nissan GT-R ' . '2024'),
            ],
            [
                // 5
                'name' => 'BMW 4-Series',
                'brand_id' => '1',
                'category_id' => '10',
                'price' => '178624',
                'description' => '',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['BMW1.jpg', 'BMW2.jpg', 'BMW3.jpg', 'BMW4.jpg', 'BMW5.jpg']),
                'avatar' => 'bmw-4-series-nobg.png',
                'slug' => Str::slug('BMW 4-Series ' . '2024'),
            ],
            [
                // 6
                'name' => 'Chevrolet Corvette',
                'brand_id' => '2',
                'category_id' => '4',
                'price' => '221035',
                'description' => '',
                'quantity' => '4',
                'producing_year' => '2024',
                'images' => json_encode(['chevrolet1.jpg', 'chevrolet2.jpg', 'chevrolet3.jpg', 'chevrolet4.jpg', 'chevrolet5.jpg']),
                'avatar' => 'chevrolet-corvette-nobg.png',
                'slug' => Str::slug('Chevrolet Corvette ' . '2024'),
            ],
            [
                // 7
                'name' => 'Dodge Hornet',
                'brand_id' => '3',
                'category_id' => '5',
                'price' => '127845',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['dodge1.jpg', 'dodge2.jpg', 'dodge3.jpg', 'dodge4.jpg', 'dodge5.jpg']),
                'avatar' => 'dodge-hornet-nobg.png',
                'slug' => Str::slug('Dodge Hornet ' . '2024'),
            ],
            [
                // 8
                'name' => 'Ferrari Daytona SP3',
                'brand_id' => '4',
                'category_id' => '10',
                'price' => '593181',
                'description' => '',
                'quantity' => '2',
                'producing_year' => '2023',
                'images' => json_encode(['ferrari1.jpg', 'ferrari2.jpg', 'ferrari3.jpg', 'ferrari4.jpg', 'ferrari5.jpg']),
                'avatar' => 'Ferrari_Daytona_SP3_nobg.png',
                'slug' => Str::slug('Ferrari Daytona SP3 ' . '2023'),
            ],
            [
                // 9
                'name' => 'Huyndai Ioniq 5',
                'brand_id' => '6',
                'category_id' => '10',
                'price' => '133175',
                'description' => '',
                'quantity' => '4',
                'producing_year' => '2024',
                'images' => json_encode(['huyndai1.jpg', 'huyndai2.jpg', 'huyndai3.jpg', 'huyndai4.jpg', 'huyndai5.jpg']),
                'avatar' => 'hyundai-ioniq-nobg.png',
                'slug' => Str::slug('Huyndai Ioniq 5 ' . '2024'),
            ],
            [
                // 10
                'name' => 'Porsche 911',
                'brand_id' => '10',
                'category_id' => '10',
                'price' => '350336',
                'description' => '',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['porsche1.jpg', 'porsche2.jpg', 'porsche3.jpg', 'porsche4.jpg', 'porsche5.jpg']),
                'avatar' => 'porsche-911-nobg.png',
                'slug' => Str::slug('Porsche 911 ' . '2024'),
            ],
            [
                // 11
                'name' => 'Toyota Highlander',
                'brand_id' => '11',
                'category_id' => '8',
                'price' => '120620',
                'description' => '',
                'quantity' => '4',
                'producing_year' => '2024',
                'images' => json_encode(['toyota1.jpg', 'toyota2.jpg', 'toyota3.jpg', 'toyota4.jpg', 'toyota5.jpg']),
                'avatar' => 'toyota-highlander-nobg.png',
                'slug' => Str::slug('Toyota Highlander ' . '2024'),
            ],
            [
                // 12
                'name' => 'Ferrari 296 GTB',
                'brand_id' => '4',
                'category_id' => '6',
                'price' => '593181',
                'description' => '',
                'quantity' => '4',
                'producing_year' => '2024',
                'images' => json_encode(['Ferrari-296-GTB-1.jpg', 'Ferrari-296-GTB-2.jpg', 'Ferrari-296-GTB-3.jpg', 'Ferrari-296-GTB-4.jpg', 'Ferrari-296-GTB-5.jpg']),
                'avatar' => 'Ferrari-296-GTB-nobg.png',
                'slug' => Str::slug('Ferrari 296 GTB ' . '2024'),
            ],
            [
                // 13
                'name' => 'Ferrari F8',
                'brand_id' => '4',
                'category_id' => '10',
                'price' => '343181',
                'description' => '',
                'quantity' => '4',
                'producing_year' => '2024',
                'images' => json_encode(['Ferrari-F8-1.jpg', 'Ferrari-F8-2.jpg', 'Ferrari-F8-3.jpg', 'Ferrari-F8-4.jpg', 'Ferrari-F8-5.jpg']),
                'avatar' => 'Ferrari-F8-Spider-nobg.png',
                'slug' => Str::slug('Ferrari F8 ' . '2024'),
            ],
            [
                // 14
                'name' => 'Ferrari SF90',
                'brand_id' => '4',
                'category_id' => '10',
                'price' => '443181',
                'description' => '',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['ferrari-sf90-1.jpg', 'ferrari-sf90-2.jpg', 'ferrari-sf90-3.jpg', 'ferrari-sf90-4.jpg', 'ferrari-sf90-5.jpg']),
                'avatar' => 'ferrari-sf90-nobg.png',
                'slug' => Str::slug('Ferrari SF90 ' . '2024'),
            ],
            [
                // 15
                'name' => 'Ferrari SF90 Stradale',
                'brand_id' => '4',
                'category_id' => '10',
                'price' => '483181',
                'description' => '',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['Ferrari-SF90-Stradale-1.jpg', 'Ferrari-SF90-Stradale-2.jpg', 'Ferrari-SF90-Stradale-3.jpg', 'Ferrari-SF90-Stradale-4.jpg', 'Ferrari-SF90-Stradale-5.jpg']),
                'avatar' => 'Ferrari-SF90-Spider-nobg.png',
                'slug' => Str::slug('Ferrari SF90 Stradale ' . '2024'),
            ],
            [
                // 16
                'name' => 'Ford F-150',
                'brand_id' => '5',
                'category_id' => '6',
                'price' => '983181',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Ford-F-150-1.jpg', 'Ford-F-150-2.jpg', 'Ford-F-150-3.jpg', 'Ford-F-150-4.jpg', 'Ford-F-150-5.jpg']),
                'avatar' => 'Ford-F-150-nobg.png',
                'slug' => Str::slug('Ford F-150 ' . '2024'),
            ],
            [
                // 17
                'name' => 'Ford Mustang GTD',
                'brand_id' => '5',
                'category_id' => '10',
                'price' => '783181',
                'description' => '',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['ford-mustang-gtd1.jpg', 'ford-mustang-gtd2.jpg', 'ford-mustang-gtd3.jpg', 'ford-mustang-gtd4.jpg', 'ford-mustang-gtd5.jpg']),
                'avatar' => 'ford-mustang-gtd-nobg.png',
                'slug' => Str::slug('Ford Mustang GTD ' . '2024'),
            ],
            [
                // 18
                'name' => 'Lamborghini Huracan',
                'brand_id' => '7',
                'category_id' => '10',
                'price' => '793181',
                'description' => '',
                'quantity' => '2',
                'producing_year' => '2024',
                'images' => json_encode(['Lamborghini-Huracan-1.jpg', 'Lamborghini-Huracan-2.jpg', 'Lamborghini-Huracan-3.jpg', 'Lamborghini-Huracan-4.jpg', 'Lamborghini-Huracan-5.jpg']),
                'avatar' => 'Lamborghini-Huracan-nobg.png',
                'slug' => Str::slug('Lamborghini Huracan ' . '2024'),
            ],
            [
                // 19
                'name' => 'Lamborghini Revuelto',
                'brand_id' => '7',
                'category_id' => '10',
                'price' => '703181',
                'description' => '',
                'quantity' => '2',
                'producing_year' => '2024',
                'images' => json_encode(['lamborghini-revuelto1.jpg', 'lamborghini-revuelto2.jpg', 'lamborghini-revuelto3.jpg', 'lamborghini-revuelto4.jpg', 'lamborghini-revuelto5.jpg']),
                'avatar' => 'lamborghini-revuelto_nobg.png',
                'slug' => Str::slug('Lamborghini Revuelto ' . '2024'),
            ],
            [
                // 20
                'name' => 'Nissan Ariya',
                'brand_id' => '9',
                'category_id' => '1',
                'price' => '603081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Nissan-Ariya1.jpg', 'Nissan-Ariya2.jpg', 'Nissan-Ariya3.jpg', 'Nissan-Ariya4.jpg', 'Nissan-Ariya5.jpg']),
                'avatar' => 'Nissan-Ariya-nobg.png',
                'slug' => Str::slug('Nissan Ariya ' . '2024'),
            ],
            [
                // 21
                'name' => 'Nissan Z',
                'brand_id' => '9',
                'category_id' => '1',
                'price' => '753081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Nissan-Z-1.jpg', 'Nissan-Z-2.jpg', 'Nissan-Z-3.jpg', 'Nissan-Z-4.jpg', 'Nissan-Z-5.jpg']),
                'avatar' => 'Nissan-Z-nobg.png',
                'slug' => Str::slug('Nissan Z ' . '2024'),
            ],
            [
                // 22
                'name' => 'BMW M8',
                'brand_id' => '1',
                'category_id' => '3',
                'price' => '703081',
                'description' => '',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['BMW-M8-1.png', 'BMW-M8-2.png', 'BMW-M8-3.png', 'BMW-M8-4.png', 'BMW-M8-5.png']),
                'avatar' => 'BMW-M8-nobg.png',
                'slug' => Str::slug('BMW M8 ' . '2024'),
            ],
            [
                // 23
                'name' => 'BMW X1',
                'brand_id' => '1',
                'category_id' => '3',
                'price' => '803081',
                'description' => '',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['BMW-X1-M35i-1.png', 'BMW-X1-M35i-2.png', 'BMW-X1-M35i-3.png', 'BMW-X1-M35i-4.png', 'BMW-X1-M35i-5.png']),
                'avatar' => 'BMW-X1-M35i-nobg.png',
                'slug' => Str::slug('BMW X1 ' . '2024'),
            ],
            [
                // 24
                'name' => 'BMW X6',
                'brand_id' => '1',
                'category_id' => '1',
                'price' => '753081',
                'description' => '',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['BMW-X6-1.png', 'BMW-X6-2.png', 'BMW-X6-3.png', 'BMW-X6-4.png', 'BMW-X6-5.png']),
                'avatar' => 'BMW-X6-nobg.png',
                'slug' => Str::slug('BMW X6 ' . '2024'),
            ],
            [
                // 25
                'name' => 'BMW XM',
                'brand_id' => '1',
                'category_id' => '3',
                'price' => '903081',
                'description' => '',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['BMW-XM-Red-1.png', 'BMW-XM-Red-2.png', 'BMW-XM-Red-3.png', 'BMW-XM-Red-4.png', 'BMW-XM-Red-5.png']),
                'avatar' => 'BMW-XM-Red-nobg.png',
                'slug' => Str::slug('BMW XM ' . '2024'),
            ],
            [
                // 26
                'name' => 'BMW i5',
                'brand_id' => '1',
                'category_id' => '4',
                'price' => '903081',
                'description' => '',
                'quantity' => '3',
                'producing_year' => '2024',
                'images' => json_encode(['bmw-5-1.png', 'bmw-5-2.png', 'bmw-5-3.png', 'bmw-5-4.png', 'bmw-5-5.png']),
                'avatar' => 'bmw-i5-nobg.png',
                'slug' => Str::slug('BMW i5 ' . '2024'),
            ],
            [
                // 27
                'name' => 'Chevrolet Blazer',
                'brand_id' => '2',
                'category_id' => '5',
                'price' => '853081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['chevrolet-blazer-1.png', 'chevrolet-blazer-2.png', 'chevrolet-blazer-3.png', 'chevrolet-blazer-4.png', 'chevrolet-blazer-5.png']),
                'avatar' => 'chevrolet-blazer-nobg.png',
                'slug' => Str::slug('Chevrolet Blazer ' . '2024'),
            ],
            [
                // 28
                'name' => 'Chevrolet Camaro',
                'brand_id' => '2',
                'category_id' => '4',
                'price' => '753081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Chevrolet-Camaro-1.png', 'Chevrolet-Camaro-2.png', 'Chevrolet-Camaro-3.png', 'Chevrolet-Camaro-4.png', 'Chevrolet-Camaro-5.png']),
                'avatar' => 'Chevrolet-Camaro-nobg.png',
                'slug' => Str::slug('Chevrolet Camaro ' . '2024'),
            ],
            [
                // 29
                'name' => 'Chevrolet Suburban',
                'brand_id' => '2',
                'category_id' => '4',
                'price' => '983081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Chevrolet-Suburban-Z71-1.png', 'Chevrolet-Suburban-Z71-2.png', 'Chevrolet-Suburban-Z71-3.png', 'Chevrolet-Suburban-Z71-4.png', 'Chevrolet-Suburban-Z71-5.png']),
                'avatar' => 'Chevrolet-Suburban-Z71-nobg.png',
                'slug' => Str::slug('Chevrolet Suburban ' . '2024'),
            ],
            [
                // 30
                'name' => 'Chevrolet Trailblazer',
                'brand_id' => '2',
                'category_id' => '6',
                'price' => '753081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['chevrolet-trailblazer-1.png', 'chevrolet-trailblazer-2.png', 'chevrolet-trailblazer-3.png', 'chevrolet-trailblazer-4.png', 'chevrolet-trailblazer-5.png']),
                'avatar' => 'chevrolet-trailblazer-nobg.png',
                'slug' => Str::slug('Chevrolet Trailblazer ' . '2024'),
            ],
            [
                // 31
                'name' => 'Chevrolet Trax',
                'brand_id' => '2',
                'category_id' => '1',
                'price' => '753081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Chevrolet-Trax-1.png', 'Chevrolet-Trax-2.png', 'Chevrolet-Trax-3.png', 'Chevrolet-Trax-4.png', 'Chevrolet-Trax-5.png']),
                'avatar' => 'Chevrolet-Trax-nobg.png',
                'slug' => Str::slug('Chevrolet Trax ' . '2024'),
            ],
            [
                // 32
                'name' => 'Dodge Avenger',
                'brand_id' => '3',
                'category_id' => '6',
                'price' => '653081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['dodge-avenger-1.png', 'dodge-avenger-2.png', 'dodge-avenger-3.png', 'dodge-avenger-4.png', 'dodge-avenger-5.png']),
                'avatar' => 'dodge-avenger-nobg.png',
                'slug' => Str::slug('Dodge Avenger' . '2024'),
            ],
            [
                // 33
                'name' => 'Dodge Challenger',
                'brand_id' => '3',
                'category_id' => '10',
                'price' => '853081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['odge-challenger-1.png', 'odge-challenger-2.png', 'odge-challenger-3.png', 'odge-challenger-4.png', 'odge-challenger-5.png']),
                'avatar' => 'dodge-challenger-nobg.png',
                'slug' => Str::slug('Dodge Challenger' . '2024'),
            ],
            [
                // 34
                'name' => 'Dodge Charger',
                'brand_id' => '3',
                'category_id' => '5',
                'price' => '853081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Dodge_Charger_1.png', 'Dodge_Charger_2.png', 'Dodge_Charger_3.png', 'Dodge_Charger_4.png', 'Dodge_Charger_5.png']),
                'avatar' => 'Dodge_Charger_nobg.png',
                'slug' => Str::slug('Dodge Charger' . '2024'),
            ],
            [
                // 35
                'name' => 'Dodge Journey',
                'brand_id' => '3',
                'category_id' => '4',
                'price' => '753081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['dodge-journey-1.png', 'dodge-journey-2.png', 'dodge-journey-3.png', 'dodge-journey-4.png', 'dodge-journey-5.png']),
                'avatar' => 'dodge-journey-nobg.png',
                'slug' => Str::slug('Dodge Journey' . '2024'),
            ],
            [
                // 36
                'name' => 'Dodge Neon',
                'brand_id' => '3',
                'category_id' => '10',
                'price' => '553081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['dodge-neon-1.png', 'dodge-neon-2.png', 'dodge-neon-3.png', 'dodge-neon-4.png', 'dodge-neon-5.png']),
                'avatar' => 'dodge-neon-nobg.png',
                'slug' => Str::slug('Dodge Neon' . '2024'),
            ],
            [
                // 37
                'name' => 'Ferrari Roma',
                'brand_id' => '4',
                'category_id' => '10',
                'price' => '853081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Ferrari-Roma-1.png', 'Ferrari-Roma-2.png', 'Ferrari-Roma-3.png', 'Ferrari-Roma-4.png', 'Ferrari-Roma-5.png']),
                'avatar' => 'Ferrari-Roma-nobg.png',
                'slug' => Str::slug('Ferrari Roma' . '2024'),
            ],
            [
                // 38
                'name' => 'Ford Bronco',
                'brand_id' => '5',
                'category_id' => '3',
                'price' => '853081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Ford-Bronco-1.png', 'Ford-Bronco-2.png', 'Ford-Bronco-3.png', 'Ford-Bronco-4.png']),
                'avatar' => 'Ford-Bronco-nobg.png',
                'slug' => Str::slug('Ford Bronco' . '2024'),
            ],
            [
                // 39
                'name' => 'Ford Edge',
                'brand_id' => '5',
                'category_id' => '1',
                'price' => '853081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Ford-Edge-1.png', 'Ford-Edge-2.png', 'Ford-Edge-3.png', 'Ford-Edge-4.png', 'Ford-Edge-5.png']),
                'avatar' => 'Ford-Edge-nobg.png',
                'slug' => Str::slug('Ford Edge' . '2024'),
            ],
            [
                // 40
                'name' => 'Ford Mustang Mach-E',
                'brand_id' => '5',
                'category_id' => '1',
                'price' => '853081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Ford-Mustang-Mach-E-1.png', 'Ford-Mustang-Mach-E-2.png', 'Ford-Mustang-Mach-E-3.png', 'Ford-Mustang-Mach-E-4.png', 'Ford-Mustang-Mach-E-5.png']),
                'avatar' => 'Ford-Mustang-Mach-E-nobg.png',
                'slug' => Str::slug('Ford Mustang Mach-E' . '2024'),
            ],
            [
                // 41
                'name' => 'Hyundai Santa Cruz',
                'brand_id' => '6',
                'category_id' => '3',
                'price' => '803081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Hyundai-Santa-Cruz-1.png', 'Hyundai-Santa-Cruz-2.png', 'Hyundai-Santa-Cruz-3.png', 'Hyundai-Santa-Cruz-4.png', 'Hyundai-Santa-Cruz-5.png']),
                'avatar' => 'Hyundai-Santa-Cruz-nobg.png',
                'slug' => Str::slug('Hyundai Santa Cruz' . '2024'),
            ],
            [
                // 42
                'name' => 'Hyundai Sonata',
                'brand_id' => '6',
                'category_id' => '2',
                'price' => '803081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Hyundai-Sonata-Hybrid-1.png', 'Hyundai-Sonata-Hybrid-2.png', 'Hyundai-Sonata-Hybrid-3.png', 'Hyundai-Sonata-Hybrid-4.png', 'Hyundai-Sonata-Hybrid-5.png']),
                'avatar' => 'Hyundai-Sonata-Hybrid-nobg.png',
                'slug' => Str::slug('Hyundai Sonata' . '2024'),
            ],
            [
                // 43
                'name' => 'Hyundai Tucson',
                'brand_id' => '6',
                'category_id' => '1',
                'price' => '703081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Hyundai-Tucson-1.png', 'Hyundai-Tucson-2.png', 'Hyundai-Tucson-3.png', 'Hyundai-Tucson-4.png', 'Hyundai-Tucson-5.png']),
                'avatar' => 'Hyundai-Tucson-nobg.png',
                'slug' => Str::slug('Hyundai Tucson' . '2024'),
            ],
            [
                // 44
                'name' => 'Hyundai Venue',
                'brand_id' => '6',
                'category_id' => '1',
                'price' => '703081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Hyundai-Venue-1.png', 'Hyundai-Venue-2.png', 'Hyundai-Venue-3.png', 'Hyundai-Venue-4.png', 'Hyundai-Venue-5.png']),
                'avatar' => 'Hyundai-Venue-nobg.png',
                'slug' => Str::slug('Hyundai Venue' . '2024'),
            ],
            [
                // 45
                'name' => 'HyundaiPalisade',
                'brand_id' => '6',
                'category_id' => '5',
                'price' => '763081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['hyundai-palisade-1.png', 'hyundai-palisade-2.png', 'hyundai-palisade-3.png', 'hyundai-palisade-4.png', 'hyundai-palisade-5.png']),
                'avatar' => 'hyundai-palisade-nobg.png',
                'slug' => Str::slug('HyundaiPalisade' . '2024'),
            ],
            [
                // 46
                'name' => 'McLaren 570S',
                'brand_id' => '8',
                'category_id' => '10',
                'price' => '963081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['hmclaren-570s-1.png']),
                'avatar' => 'mclaren-570s-nobg.png',
                'slug' => Str::slug('McLaren 570S' . '2024'),
            ],
            [
                // 47
                'name' => 'McLaren 600LT',
                'brand_id' => '8',
                'category_id' => '10',
                'price' => '963081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['mclaren-600lt-1.png']),
                'avatar' => 'mclaren-600lt-nobg.png',
                'slug' => Str::slug('McLaren 600LT' . '2024'),
            ],
            [
                // 48
                'name' => 'McLaren 750S',
                'brand_id' => '8',
                'category_id' => '10',
                'price' => '963081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['McLaren-750S-1.png', 'McLaren-750S-2.png', 'McLaren-750S-3.png', 'McLaren-750S-4.png', 'McLaren-750S-5.png']),
                'avatar' => 'McLaren-750S-nobg.png',
                'slug' => Str::slug('McLaren 750S' . '2024'),
            ],
            [
                // 49
                'name' => 'McLaren Artura',
                'brand_id' => '8',
                'category_id' => '10',
                'price' => '963081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['McLaren-Artura-1.png', 'McLaren-Artura-2.png', 'McLaren-Artura-3.png', 'McLaren-Artura-4.png', 'McLaren-Artura-5.png']),
                'avatar' => 'McLaren-Artura-nobg.png',
                'slug' => Str::slug('McLaren Artura' . '2024'),
            ],
            [
                // 50
                'name' => 'McLaren GT',
                'brand_id' => '8',
                'category_id' => '10',
                'price' => '963081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['McLaren-GT-1.png', 'McLaren-GT-2.png', 'McLaren-GT-3.png', 'McLaren-GT-4.png', 'McLaren-GT-5.png']),
                'avatar' => 'McLaren-GT-nobg.png',
                'slug' => Str::slug('McLaren GT' . '2024'),
            ],
            [
                // 51
                'name' => 'Mercedes-Benz E-Class',
                'brand_id' => '12',
                'category_id' => '5',
                'price' => '763081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Mercedes-Benz-E-Class-1.png', 'Mercedes-Benz-E-Class-2.png', 'Mercedes-Benz-E-Class-3.png', 'Mercedes-Benz-E-Class-4.png', 'Mercedes-Benz-E-Class-5.png']),
                'avatar' => 'Mercedes-Benz-E-Class-nobg.png',
                'slug' => Str::slug('Mercedes-Benz E-Class' . '2024'),
            ],
            [
                // 52
                'name' => 'Mercedes-Benz E-Class Blue',
                'brand_id' => '12',
                'category_id' => '5',
                'price' => '763081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['mercedes-benz-e250-1.png', 'mercedes-benz-e250-2.png', 'mercedes-benz-e250-3.png', 'mercedes-benz-e250-4.png', 'mercedes-benz-e250-5.png']),
                'avatar' => 'mercedes-benz-e250-nobg.png',
                'slug' => Str::slug('Mercedes-Benz E-Class Blue' . '2024'),
            ],
            [
                // 53
                'name' => 'Mercedes-Benz EQB-Class',
                'brand_id' => '12',
                'category_id' => '1',
                'price' => '763081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['mercedes-benz-eqb-1.png', 'mercedes-benz-eqb-2.png', 'mercedes-benz-eqb-3.png', 'mercedes-benz-eqb-4.png', 'mercedes-benz-eqb-5.png']),
                'avatar' => 'mercedes-benz-eqb-nobg.png',
                'slug' => Str::slug('Mercedes-Benz EQB-Class' . '2024'),
            ],
            [
                // 54
                'name' => 'Mercedes-Benz GLE-Class',
                'brand_id' => '12',
                'category_id' => '1',
                'price' => '763081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Mercedes-Benz-AMG-GLE-1.png', 'Mercedes-Benz-AMG-GLE-2.png', 'Mercedes-Benz-AMG-GLE-3.png', 'Mercedes-Benz-AMG-GLE-4.png', 'Mercedes-Benz-AMG-GLE-5.png']),
                'avatar' => 'Mercedes-Benz-AMG-GLE-nobg.png',
                'slug' => Str::slug('Mercedes-Benz GLE-Class' . '2024'),
            ],
            [
                // 55
                'name' => 'Mercedes-Benz R-Class',
                'brand_id' => '12',
                'category_id' => '1',
                'price' => '763081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['mercedes-benz-r-1.png', 'mercedes-benz-r-2.png', 'mercedes-benz-r-3.png', 'mercedes-benz-r-4.png', 'mercedes-benz-r-5.png']),
                'avatar' => 'mercedes-benz-r-nobg.png',
                'slug' => Str::slug('Mercedes-Benz R-Class' . '2024'),
            ],
            [
                // 56
                'name' => 'Mercedes-Benz SLS AMG',
                'brand_id' => '12',
                'category_id' => '1',
                'price' => '763081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['mercedes-benz-sls-amg-1.png', 'mercedes-benz-sls-amg-2.png', 'mercedes-benz-sls-amg-3.png', 'mercedes-benz-sls-amg-4.png', 'mercedes-benz-sls-amg-5.png']),
                'avatar' => 'mercedes-benz-sls-amg-nobg.png',
                'slug' => Str::slug('Mercedes-Benz SLS AMG' . '2024'),
            ],
            [
                // 57
                'name' => 'Nissan Altima',
                'brand_id' => '9',
                'category_id' => '2',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Nissan-Altima-1.png', 'Nissan-Altima-2.png', 'Nissan-Altima-3.png', 'Nissan-Altima-4.png', 'Nissan-Altima-5.png']),
                'avatar' => 'Nissan-Altima-nobg.png',
                'slug' => Str::slug('Nissan Altima' . '2024'),
            ],
            [
                // 58
                'name' => 'Nissan Maxima',
                'brand_id' => '9',
                'category_id' => '2',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Nissan-Maxima-1.png', 'Nissan-Maxima-2.png', 'Nissan-Maxima-3.png', 'Nissan-Maxima-4.png', 'Nissan-Maxima-5.png']),
                'avatar' => 'Nissan-Maxima-nobg.png',
                'slug' => Str::slug('Nissan Maxima' . '2024'),
            ],
            [
                // 59
                'name' => 'Nissan Versa',
                'brand_id' => '9',
                'category_id' => '5',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Nissan-Versa-1.png', 'Nissan-Versa-2.png', 'Nissan-Versa-3.png', 'Nissan-Versa-4.png', 'Nissan-Versa-5.png']),
                'avatar' => 'Nissan-Versa-nobg.png',
                'slug' => Str::slug('Nissan Versa' . '2024'),
            ],
            [
                // 60
                'name' => 'Porsche 718 Boxster',
                'brand_id' => '10',
                'category_id' => '4',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Porsche-718-Boxster-1.png', 'Porsche-718-Boxster-2.png', 'Porsche-718-Boxster-3.png', 'Porsche-718-Boxster-4.png', 'Porsche-718-Boxster-5.png']),
                'avatar' => 'Porsche-718-Boxster-nobg.png',
                'slug' => Str::slug('Porsche 718 Boxster' . '2024'),
            ],
            [
                // 61
                'name' => 'Porsche Carrera GT',
                'brand_id' => '10',
                'category_id' => '10',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['porsche-carrera-gt-1.png', 'porsche-carrera-gt-2.png', 'porsche-carrera-gt-3.png', 'porsche-carrera-gt-4.png', 'porsche-carrera-gt-5.png']),
                'avatar' => 'porsche-carrera-gt-nobg.png',
                'slug' => Str::slug('Porsche Carrera GT' . '2024'),
            ],
            [
                // 62
                'name' => 'Porsche Cayenne Diesel',
                'brand_id' => '10',
                'category_id' => '1',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['porsche-cayenne-diesel-1.png', 'porsche-cayenne-diesel-2.png', 'porsche-cayenne-diesel-3.png', 'porsche-cayenne-diesel-4.png', 'porsche-cayenne-diesel-5.png']),
                'avatar' => 'porsche-cayenne-diesel-nobg.png',
                'slug' => Str::slug('Porsche Cayenne Diesel' . '2024'),
            ],
            [
                // 63
                'name' => 'Porsche Panamera',
                'brand_id' => '10',
                'category_id' => '6',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Porsche-Panamera-1.png', 'Porsche-Panamera-2.png', 'Porsche-Panamera-3.png', 'Porsche-Panamera-4.png', 'Porsche-Panamera-5.png']),
                'avatar' => 'Porsche-Panamera-nobg.png',
                'slug' => Str::slug('Porsche Panamera' . '2024'),
            ],
            [
                // 64
                'name' => 'Porsche Taycan',
                'brand_id' => '10',
                'category_id' => '6',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Porsche-Taycan-1.png', 'Porsche-Taycan-2.png', 'Porsche-Taycan-3.png', 'Porsche-Taycan-4.png', 'Porsche-Taycan-5.png']),
                'avatar' => 'Porsche-Taycan-nobg.png',
                'slug' => Str::slug('Porsche Taycan' . '2024'),
            ],
            [
                // 65
                'name' => 'Toyota Camry',
                'brand_id' => '11',
                'category_id' => '2',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Toyota-Camry-1.png', 'Toyota-Camry-2.png', 'Toyota-Camry-3.png', 'Toyota-Camry-4.png', 'Toyota-Camry-5.png']),
                'avatar' => 'Toyota-Camry-nobg.png',
                'slug' => Str::slug('Toyota Camry' . '2024'),
            ],
            [
                // 66
                'name' => 'Toyota Crown',
                'brand_id' => '11',
                'category_id' => '5',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['toyota-crown-1.png', 'toyota-crown-2.png', 'toyota-crown-3.png', 'toyota-crown-4.png', 'toyota-crown-5.png']),
                'avatar' => 'toyota-crown-nobg.png',
                'slug' => Str::slug('Toyota Crown' . '2024'),
            ],
            [
                // 67
                'name' => 'Toyota Mirai',
                'brand_id' => '11',
                'category_id' => '8',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Toyota-Mirai-1.png', 'Toyota-Mirai-2.png', 'Toyota-Mirai-3.png', 'Toyota-Mirai-4.png', 'Toyota-Mirai-5.png']),
                'avatar' => 'Toyota-Mirai-nobg.png',
                'slug' => Str::slug('Toyota Mirai' . '2024'),
            ],
            [
                // 68
                'name' => 'Toyota RAV4',
                'brand_id' => '11',
                'category_id' => '1',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['toyota-rav4-1.png', 'toyota-rav4-2.png', 'toyota-rav4-3.png', 'toyota-rav4-4.png', 'toyota-rav4-5.png']),
                'avatar' => 'toyota-rav4-nobg.png',
                'slug' => Str::slug('Toyota RAV4' . '2024'),
            ],
            [
                // 69
                'name' => 'Toyota Supra',
                'brand_id' => '11',
                'category_id' => '4',
                'price' => '793081',
                'description' => '',
                'quantity' => '5',
                'producing_year' => '2024',
                'images' => json_encode(['Toyota-GR-Supra-1.png', 'Toyota-GR-Supra-2.png', 'Toyota-GR-Supra-3.png', 'Toyota-GR-Supra-4.png', 'Toyota-GR-Supra-5.png']),
                'avatar' => 'Toyota-GR-Supra-nobg.png',
                'slug' => Str::slug('Toyota Supra' . '2024'),
            ],
        ]);
    }
}
