<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SafetySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table("safety") -> insert([
            [
                 //Ford Mustang
                "car_id" => "1",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"

            ],
            [
                //Lamborghini Huracan
                "car_id" => "2",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"

                
            ],
            [
                //McLaren 720S
                "car_id" => "3",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"

            ],
            [
                //Nissan GT-R
                "car_id" => "4",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"

            ],
            [
                //BMW
                "car_id" => "5",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"

            ],
            [
                //Chevrolet
                "car_id" => "6",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"

            ],
            [
                //Dodge
                "car_id" => "7",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"

            ],
            [
                //Ferrari
                "car_id" => "8",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                //Huyndai
                "car_id" => "9",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                //Porsche
                "car_id" => "10",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                //Toyota
                "car_id" => "11",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "4"
            ],
            [
                //Ferrari 296 GTB
                "car_id" => "12",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                //Ferrari F8
                "car_id" => "13",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                //Ferrari SF90
                "car_id" => "14",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                //Ferrari SF90 Stradale
                "car_id" => "15",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                //Ford F-150
                "car_id" => "16",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "4"
            ],
            [
                //Ford Mustang GTD
                "car_id" => "17",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                //Lamborghini Huracan
                "car_id" => "18",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                //Lamborghini Revuelto
                "car_id" => "19",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                //Nissan Ariya
                "car_id" => "20",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                //Nissan Z
                "car_id" => "21",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "22",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "23",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "24",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "25",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "26",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "27",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "4"
            ],
            [
                "car_id" => "28",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "29",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "30",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "4",
                "NHTSA_rating_rollover" => "4"
            ],
            [
                "car_id" => "31",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "4",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "32",
                "IIHS_best_pick" => "1",
                "IIHS_front_small_overlap" => "Acceptable",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "Good",
                "NHTSA_rating_front_passenger" => "3",
                "NHTSA_rating_overall" => "4",
                "NHTSA_rating_rollover" => "4"
            ],
            [
                "car_id" => "33",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Acceptable",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "Acceptable",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "4",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "34",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "35",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "Poor",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "Good",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "4",
                "NHTSA_rating_rollover" => "4"
            ],
            [
                "car_id" => "36",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Marginal",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "4",
                "NHTSA_rating_overall" => "N/R",
                "NHTSA_rating_rollover" => "4"
            ],
            [
                "car_id" => "37",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "38",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "4",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "39",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "4",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "40",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "41",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "42",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "43",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "4",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "44",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "4",
                "NHTSA_rating_rollover" => "4"
            ],
            [
                "car_id" => "45",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "Good",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "Marginal",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "4",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "46",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "47",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "48",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "49",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "50",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "51",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "52",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "53",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "54",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "4",
                "NHTSA_rating_rollover" => "5"
            ],
            [
                "car_id" => "55",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "4"

            ],
            [
                "car_id" => "56",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "4"

            ],
            [
                "car_id" => "57",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "4"

            ],
            [
                "car_id" => "58",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Poor",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "5"

            ],
            [
                "car_id" => "59",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "5"

            ],
            [
                "car_id" => "60",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "4"

            ],
            [
                "car_id" => "61",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "62",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"

            ],
            [
                "car_id" => "63",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"

            ],
            [
                "car_id" => "64",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"

            ],
            [
                "car_id" => "65",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"

            ],
            [
                "car_id" => "66",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "Good",
                "IIHS_overall_side_crash" => "Poor",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "5"

            ],
            [
                "car_id" => "67",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"


            ],
            [
                "car_id" => "68",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "N/R",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "N/R",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "Not Rated",
                "NHTSA_rating_rollover" => "Not Rated"
            ],
            [
                "car_id" => "69",
                "IIHS_best_pick" => "0",
                "IIHS_front_small_overlap" => "N/R",
                "IIHS_rear_crash" => "Good",
                "IIHS_rating_front_driver" => "",
                "IIHS_rating_front_side" => "",
                "IIHS_rating_rear_side" => "",
                "IIHS_front_moderate_overlap" => "N/R",
                "IIHS_overall_side_crash" => "Good",
                "IIHS_roof_strength" => "N/R",
                "NHTSA_rating_front_passenger" => "Not Rated",
                "NHTSA_rating_overall" => "5",
                "NHTSA_rating_rollover" => "4"

            ],
        ]);
    }
}
